source 'https://supermarket.chef.io'

metadata

cookbook 'test', path: './test'
cookbook 'formatron_sensu', git: 'https://github.com/formatron/sensu-cookbook.git'
cookbook 'formatron_beats', git: 'https://github.com/formatron/beats-cookbook.git'
cookbook 'formatron_filebeat', git: 'https://github.com/formatron/filebeat-cookbook.git'
cookbook 'formatron_common', git: 'https://github.com/formatron/common-cookbook.git'
cookbook 'formatron_erlang', git: 'https://github.com/formatron/erlang-cookbook.git'
cookbook 'formatron_rabbitmq', git: 'https://github.com/formatron/rabbitmq-cookbook.git'
cookbook 'formatron_redis', git: 'https://github.com/formatron/redis-cookbook.git'
cookbook 'formatron_postgresql', git: 'https://github.com/formatron/postgresql-cookbook.git'
cookbook 'formatron_elasticsearch', git: 'https://github.com/formatron/elasticsearch-cookbook.git'
cookbook 'formatron_logstash', git: 'https://github.com/formatron/logstash-cookbook.git'
cookbook 'formatron_kibana', git: 'https://github.com/formatron/kibana-cookbook.git'
cookbook 'formatron_uchiwa', git: 'https://github.com/formatron/uchiwa-cookbook.git'
cookbook 'formatron_graphite', git: 'https://github.com/formatron/graphite-cookbook.git'
cookbook 'formatron_grafana', git: 'https://github.com/formatron/grafana-cookbook.git'
cookbook 'formatron_apache', git: 'https://github.com/formatron/apache-cookbook.git'
cookbook 'formatron_elk', git: 'https://github.com/formatron/elk-cookbook.git'
