name 'formatron_monitor'
version '0.1.6'
description 'Formatron monitor cookbook'
maintainer 'Peter Halliday'
maintainer_email 'pghalliday@gmail.com'
source_url 'https://github.com/formatron/monitor-cookbook'
issues_url 'https://github.com/formatron/monitor-cookbook/issues'
supports 'ubuntu'
depends 'java'
depends 'build-essential'
depends 'formatron_common'
depends 'formatron_apache'
depends 'formatron_erlang'
depends 'formatron_rabbitmq'
depends 'formatron_redis'
depends 'formatron_postgresql'
depends 'formatron_elasticsearch'
depends 'formatron_logstash'
depends 'formatron_kibana'
depends 'formatron_sensu'
depends 'formatron_uchiwa'
depends 'formatron_graphite'
depends 'formatron_grafana'
depends 'formatron_elk'
